### ISSUE TITLE
[question] What is your way to order error messages?

### ISSUE THREAD

**Issue by gaydenko** [wrapp-archive/validate.js#14]
For complicated form error messages ordering by attributes given order looks handy (if not say "obligatory"). What is your way to order error messages?

**Comment by ansman** [comment]
Do you mean attribute order or error message order?

The attributes don't have an order since they are just object keys which are unordered.
Same goes for the actual messages within an attribute.
They will have the same order as the validators have for that attribute which is implementation specific.
